//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int IdWareHouse { get; set; }
        public string HouseName { get; set; }
        public Nullable<int> AdressID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
    }
}
